DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE SHIP_RATE CASCADE CONSTRAINTS;
DROP TABLE TAX CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_REVIEW CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE ORDER_TABLE CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_REVIEW CASCADE CONSTRAINTS;

SET ECHO;
SET FEEDBACK;

CREATE TABLE CUSTOMER
(
CUSTOMER# NUMBER(10) NOT NULL,
FIRST_NAME VARCHAR2(10) NOT NULL,
LAST_NAME VARCHAR2(10) NOT NULL,
PHONE VARCHAR2(12) NOT NULL,
ADDRESS_ VARCHAR2(20) NOT NULL,
CITY VARCHAR2(15) NOT NULL,
PROVINCE  CHAR(6) NOT NULL,
POSTAL_CODE CHAR(6) NOT NULL,
TIMBER_NUMBER NUMBER(1) NOT NULL,
     CONSTRAINT CUSTOMER#_PK PRIMARY KEY(CUSTOMER#)
); 

CREATE TABLE SUPPLIER
(
SUPPLIER# NUMBER(10),
NAME VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(20) NOT NULL,
CITY VARCHAR2(20),
PROVINCE CHAR(2),
    CONSTRAINT SUPPLIER_PK PRIMARY KEY(SUPPLIER#),
    CONSTRAINT PROVINCE_CK CHECK(PROVINCE in ('BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NB', 'NS', 'BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NB', 'NS',
        'NL', 'NT', 'NU', 'PE', 'YT'))
);

CREATE TABLE PRODUCT
(
PRODUCT# NUMBER(10),
TITLE VARCHAR2(50) NOT NULL,
DESCRIPTION_ VARCHAR2(100) NOT NULL,
PRICE NUMBER(10,2) NOT NULL,
WEIGHT_ NUMBER(5,2) NOT NULL,
TAX_EXEMPTED NUMBER(1) NOT NULL,
    CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT#),
    CONSTRAINT PRICE_CK CHECK(PRICE>0),
    CONSTRAINT TAX_EXEMPTED_CK CHECK(TAX_EXEMPTED in (0,1))
);

CREATE TABLE SHIP_RATE
(
SHIPRATE# NUMBER(10),
MIN_WEIGHT NUMBER(4,1) NOT NULL,
MAX_WEIGHT NUMBER(4,1) NOT NULL,
PRICE NUMBER(6,2),
     CONSTRAINT SHIPRATE#_PK PRIMARY KEY(SHIPRATE#),
     CONSTRAINT MIN_MAX_WEIGHT_CK CHECK(MAX_WEIGHT >= MIN_WEIGHT)
); 

CREATE TABLE TAX
(
PROV CHAR(2),
PROV_HST NUMBER(5,3),
PROV_GST NUMBER(5,3),
     CONSTRAINT TAX_PK PRIMARY KEY(PROV)
); 

CREATE TABLE PRODUCT_REVIEW
(
REVIEW# NUMBER,
PRODUCT# NUMBER(10),
RATING NUMBER(1),
COMMENTS VARCHAR2(1000),
     CONSTRAINT PRODUCT_REVIEW_PK PRIMARY KEY(REVIEW#),
     CONSTRAINT PRODUCT_REVIEW_PRODUCT#_FK FOREIGN KEY(PRODUCT#) REFERENCES PRODUCT(PRODUCT#),
     CONSTRAINT PRODUCT_REVIEW_RATING_CK CHECK(RATING in (1,2,3,4,5))
);

CREATE TABLE ORDER_ITEM
(
ORDER# NUMBER(10),
PRODUCT# NUMBER(10),
QUANTITY NUMBER(3) NOT NULL,
    CONSTRAINT ORDER_ITEM_PK PRIMARY KEY(ORDER#),
    CONSTRAINT ORDER_ITEM_FK FOREIGN KEY(PRODUCT#) REFERENCES PRODUCT(PRODUCT#),
    CONSTRAINT QUANTITY_ORDER_ITEM_CK CHECK(QUANTITY > 0)
);

CREATE TABLE PRODUCT_SUPPLIER
(
PRODUCT# NUMBER(10),
SUPPLIER# NUMBER(10),
QUANTITY NUMBER(3),
DAYS_TODELIVER NUMBER(2),
    CONSTRAINT PRODUCT_SUPPLIER_PK PRIMARY KEY(PRODUCT#, SUPPLIER#),
    CONSTRAINT PRODCT_PRODUCT_SUPPLIER_FK FOREIGN KEY(PRODUCT#)
        REFERENCES PRODUCT(PRODUCT#),
    CONSTRAINT SUPPLIER_PRODUCT_SUPPLIER_FK FOREIGN KEY(SUPPLIER#)
        REFERENCES SUPPLIER(SUPPLIER#),
    CONSTRAINT QUANTITY_CK CHECK(QUANTITY>=0),
    CONSTRAINT DAYS_TODELIVER_CK CHECK(DAYS_TODELIVER>=0)
);

CREATE TABLE ORDER_TABLE
(
ORDER# NUMBER(10),
CUSTOMER# NUMBER(10),
ORDER_DATE DATE,
TAX NUMBER(10,2),
SHIPRATE# NUMBER NOT NULL,
PROV CHAR(2) NOT NULL,
     CONSTRAINT ORDER_TABLE_PK PRIMARY KEY(ORDER#, CUSTOMER#),
     CONSTRAINT SHIPRATE_ORDER_FK FOREIGN KEY(SHIPRATE#) REFERENCES SHIP_RATE(SHIPRATE#),
     CONSTRAINT CUSTOMER#_ORDER_FK FOREIGN KEY(CUSTOMER#) REFERENCES CUSTOMER(CUSTOMER#),
     CONSTRAINT ORDER_ORDER_TABLE_FK FOREIGN KEY(ORDER#) REFERENCES ORDER_ITEM(ORDER#),
     CONSTRAINT PROV_ORDER_FK FOREIGN KEY(PROV) REFERENCES TAX(PROV)
); 

CREATE TABLE CUSTOMER_REVIEW
(
CUSTOMER# NUMBER(10),
REVIEW# NUMBER,
DATE_REVIEW DATE,
     CONSTRAINT CUSTOMER_REVIEW_PK PRIMARY KEY(CUSTOMER#, REVIEW#),
     CONSTRAINT CUSTOMER_REVIEW_CUSTOMER#_FK FOREIGN KEY(CUSTOMER#) REFERENCES CUSTOMER(CUSTOMER#),
     CONSTRAINT CUSTOMER_REVIEW_REVIEW#_FK FOREIGN KEY(REVIEW#) REFERENCES PRODUCT_REVIEW(REVIEW#)
); 
